plugins:
  - jest
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: off
  import/extensions: off
  import/no-named-as-default: off
  import/no-unresolved: off
  consistent-return: off
  import/named: off
  implicit-arrow-linebreak: off
  import/no-extraneous-dependencies: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

